stages:
  data-split:
    cmd: python3 src/data_split.py
    deps:
    - data/train.csv
    - src/data_split.py
    outs:
    - data/processed_data/x_test.npy
    - data/processed_data/x_train.npy
    - data/processed_data/y_test.npy
    - data/processed_data/y_train.npy
  model-training:
    cmd: python3 src/model_training.py
    deps:
      - data/processed_data/x_train.npy
      - data/processed_data/y_train.npy
      - src/model_training.py
    params:
      - model-training.batch_size
      - model-training.epochs
      - model-training.val_split
    outs:
      - models/toxicity_classifier.h5
      - models/tokenizer.pkl
    plots:
      - log_loss.jpg:
          cache: false
      - auc.jpg:
          cache: false
  model-evaluation:
    cmd: python3 src/model_evaluation.py
    deps:
      - data/processed_data/x_test.npy
      - data/processed_data/y_test.npy
      - models/toxicity_classifier.h5
      - src/model_evaluation.py
    plots:
      - confusion_matrix.jpg:
          cache: false
      - auc_roc.jpg:
          cache: false
    metrics:
      - scores.json:
          cache: false